In [14]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
import joblib

# Step 1: Load the dataset
df = pd.read_csv("generator_health_dataset.csv")  # Update path if needed

# Step 2: Features (X) and target (y)
X = df.drop("Status", axis=1)
y = df["Status"]  # Status: 0 = Healthy, 1 = Faulty, 2 = Maintenance (if present)

# Step 3: Split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Train the Random Forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Step 5: Evaluate the model
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

# Step 6: Save the trained model
joblib.dump(model, "generator_rf_model.pkl")
print("✅ Model saved as 'generator_rf_model.pkl'")


              precision    recall  f1-score   support

           0       1.00      1.00      1.00       145
           1       0.97      1.00      0.99        39
           2       1.00      0.94      0.97        16

    accuracy                           0.99       200
   macro avg       0.99      0.98      0.99       200
weighted avg       1.00      0.99      0.99       200

✅ Model saved as 'generator_rf_model.pkl'


In [19]:
import joblib 
import numpy as np

# Step 1: Load the saved model
model = joblib.load("generator_rf_model.pkl")

# Step 2: Define test cases (Voltage, Current, Frequency, Load, Temperature)
test_cases = [
    [410.9,76.53,50.17,62.97,49.62],   
    [382.58,129.44,49.27,100.0,79.88],  
    [442.51,181.58,51.43,100.29,94.84]   
]

# Step 3: Status labels
status_map = {
    0: "Healthy",
    1: "Faulty",
    2: "Maintenance"
}

# Step 4: Predict and print results
for idx, test_sample in enumerate(test_cases, 1):
    sample_array = np.array(test_sample).reshape(1, -1)
    prediction = model.predict(sample_array)[0]
    status = status_map.get(prediction, "Unknown")
    print(f"Test Case {idx}: Input = {test_sample} → Predicted Status: {status}")


Test Case 1: Input = [410.9, 76.53, 50.17, 62.97, 49.62] → Predicted Status: Healthy
Test Case 2: Input = [382.58, 129.44, 49.27, 100.0, 79.88] → Predicted Status: Faulty
Test Case 3: Input = [442.51, 181.58, 51.43, 100.29, 94.84] → Predicted Status: Maintenance


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [20]:
import pandas as pd

# Load the newly uploaded conveyor belt dataset
file_path = "conveyor_belt_data.csv"
conveyor_df = pd.read_csv(file_path)

# Display basic info and the first few rows
conveyor_df.info(), conveyor_df.head()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Vibration    1000 non-null   float64
 1   Current      1000 non-null   float64
 2   Speed        1000 non-null   float64
 3   BeltTension  1000 non-null   float64
 4   Status       1000 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 39.2 KB


(None,
    Vibration  Current  Speed  BeltTension  Status
 0       0.67    10.64   1.23       550.53       0
 1       1.86    21.09   1.58       350.56       1
 2       0.73     7.18   1.35       488.71       0
 3       1.77    10.79   1.21       474.23       0
 4       0.82     9.42   1.14       592.61       0)

In [21]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
df = pd.read_csv("conveyor_belt_data.csv")

# Separate features and target
X = df.drop("Status", axis=1)
y = df["Status"]

# Split into training and test sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Create and train the Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate the model
print("Classification Report:\n")
print(classification_report(y_test, y_pred, target_names=["Healthy", "Maintenance", "Fault"]))

print("Confusion Matrix:\n")
print(confusion_matrix(y_test, y_pred))


Classification Report:

              precision    recall  f1-score   support

     Healthy       1.00      1.00      1.00       136
 Maintenance       1.00      1.00      1.00        43
       Fault       1.00      1.00      1.00        21

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

Confusion Matrix:

[[136   0   0]
 [  0  43   0]
 [  0   0  21]]


In [23]:
import joblib

# Save the model to a file
joblib.dump(rf_model, "conveyor_belt_model.pkl")

# To load it later
# loaded_model = joblib.load("random_forest_model.pkl")


['conveyor_belt_model.pkl']

In [24]:
import joblib
import numpy as np

# Load the model
model = joblib.load("conveyor_belt_model.pkl")

# Define your new sample: [Vibration, Current, Speed, BeltTension]
new_sample = np.array([[1.2, 15.5, 1.4, 500.0]])

# Predict
prediction = model.predict(new_sample)[0]

# Map prediction to label
class_names = ["Healthy", "Maintenance", "Fault"]
predicted_label = class_names[prediction]

print(f"Predicted Status: {predicted_label}")


Predicted Status: Healthy


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [25]:
import joblib
import numpy as np

# Load the model
model = joblib.load("conveyor_belt_model.pkl")

# Define your new sample: [Vibration, Current, Speed, BeltTension]
new_sample = np.array([[1.86,21.09,1.58,350.56]])

# Predict
prediction = model.predict(new_sample)[0]

# Map prediction to label
class_names = ["Healthy", "Maintenance", "Fault"]
predicted_label = class_names[prediction]

print(f"Predicted Status: {predicted_label}")


Predicted Status: Maintenance


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [26]:
import joblib
import numpy as np

# Load the model
model = joblib.load("conveyor_belt_model.pkl")

# Define your new sample: [Vibration, Current, Speed, BeltTension]
new_sample = np.array([[3.09,32.65,1.74,270.22]])

# Predict
prediction = model.predict(new_sample)[0]

# Map prediction to label
class_names = ["Healthy", "Maintenance", "Fault"]
predicted_label = class_names[prediction]

print(f"Predicted Status: {predicted_label}")


Predicted Status: Fault


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [1]:
# Step 1: Import libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib  # For saving the model

# Step 2: Load the dataset
df = pd.read_csv("elevator_machine_data.csv")

# Step 3: Map status codes to labels
status_map = {0: 'healthy', 1: 'maintenance', 2: 'fault'}
df['Status'] = df['Status'].map(status_map)

# Step 4: Split into features and target
X = df[['Vibration', 'Current', 'CycleCount']]
y = df['Status']

# Step 5: Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Step 6: Initialize and train Random Forest model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# Step 7: Make predictions
y_pred = rf_model.predict(X_test)

# Step 8: Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Step 9 (Optional): Save the trained model
joblib.dump(rf_model, "elevator.pkl")
print("Model saved as elevator.pkl")


Accuracy: 1.0

Confusion Matrix:
 [[ 24   0   0]
 [  0 134   0]
 [  0   0  42]]

Classification Report:
               precision    recall  f1-score   support

       fault       1.00      1.00      1.00        24
     healthy       1.00      1.00      1.00       134
 maintenance       1.00      1.00      1.00        42

    accuracy                           1.00       200
   macro avg       1.00      1.00      1.00       200
weighted avg       1.00      1.00      1.00       200

Model saved as elevator.pkl


In [2]:
import joblib
import pandas as pd

# Step 1: Load the trained model
model = joblib.load("elevator.pkl")

# Step 2: Define new sample data (same features as used in training)
# Format: [Vibration, Current, CycleCount]
new_data = pd.DataFrame([
    [0.85, 22.5, 200],   # example 1
    [2.1, 45.0, 600],    # example 2
    [1.5, 32.0, 350]     # example 3
], columns=['Vibration', 'Current', 'CycleCount'])

# Step 3: Make predictions
predictions = model.predict(new_data)

# Step 4: Display results
for i, pred in enumerate(predictions):
    print(f"Sample {i+1} → Predicted Status: {pred}")


Sample 1 → Predicted Status: healthy
Sample 2 → Predicted Status: fault
Sample 3 → Predicted Status: maintenance


In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

# Load the dataset
df = pd.read_csv("cnc_machine_data.csv")

# Separate features and target
X = df.drop("Status", axis=1)
y = df["Status"]

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Scale the features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train Random Forest classifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled, y_train)

# Make predictions
y_pred = rf_model.predict(X_test_scaled)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))


Confusion Matrix:
[[135   1   0]
 [  0  40   0]
 [  0   0  24]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      1.00       136
           1       0.98      1.00      0.99        40
           2       1.00      1.00      1.00        24

    accuracy                           0.99       200
   macro avg       0.99      1.00      0.99       200
weighted avg       1.00      0.99      1.00       200



In [5]:
import joblib

# Save the trained model
joblib.dump(rf_model, "cnc.pkl")

# Save the scaler too (important for preprocessing test data later)
joblib.dump(scaler, "scaler.pkl")


['scaler.pkl']

In [7]:
import joblib
import numpy as np

# Load model and scaler
rf_model = joblib.load("cnc.pkl")
scaler = joblib.load("scaler.pkl")

# Map numeric predictions to labels
status_labels = {0: "Healthy", 1: "Maintenance", 2: "Fault"}

# Example input: [RPM, Feed_Rate, Vibration, Temperature, Torque]
sample_data = np.array([[2200, 0.2, 1.0, 45.0, 22.0]])

# Scale the input data
sample_scaled = scaler.transform(sample_data)

# Predict
prediction = rf_model.predict(sample_scaled)

# Get readable result
predicted_status = status_labels[prediction[0]]

print("Predicted Machine Status:", predicted_status)


Predicted Machine Status: Healthy


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [8]:
import joblib
import numpy as np

# Load model and scaler
rf_model = joblib.load("cnc.pkl")
scaler = joblib.load("scaler.pkl")

# Map numeric predictions to labels
status_labels = {0: "Healthy", 1: "Maintenance", 2: "Fault"}

# Example input: [RPM, Feed_Rate, Vibration, Temperature, Torque]
sample_data = np.array([[893.94,0.338,2.1,57.91,49.17]])

# Scale the input data
sample_scaled = scaler.transform(sample_data)

# Predict
prediction = rf_model.predict(sample_scaled)

# Get readable result
predicted_status = status_labels[prediction[0]]

print("Predicted Machine Status:", predicted_status)


Predicted Machine Status: Maintenance


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [9]:
import joblib
import numpy as np

# Load model and scaler
rf_model = joblib.load("cnc.pkl")
scaler = joblib.load("scaler.pkl")

# Map numeric predictions to labels
status_labels = {0: "Healthy", 1: "Maintenance", 2: "Fault"}

# Example input: [RPM, Feed_Rate, Vibration, Temperature, Torque]
sample_data = np.array([[5275.22,0.42,2.908,85.49,6.94]])

# Scale the input data
sample_scaled = scaler.transform(sample_data)

# Predict
prediction = rf_model.predict(sample_scaled)

# Get readable result
predicted_status = status_labels[prediction[0]]

print("Predicted Machine Status:", predicted_status)


Predicted Machine Status: Fault


c:\Users\saiki\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
